version: '3'
services:
  db:
    image: 'postgres:latest'
    # network_mode: "host"

    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: project 
      
    volumes:
      - ./db-data/:/db-data/

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      retries: 5
      start_period: 5s

    # ports:
    #   - "5432:5432"
    networks:
      back_network:
        ipv4_address: 172.16.58.11

  back:
    build: ./backend
    restart: always

    # network_mode: "host"

    volumes:
      - .:/app/
    depends_on:
      db:
        condition: service_healthy

    networks:
      back_network:
        ipv4_address: 172.16.58.12

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "1234:80"
    depends_on:
      - db
    
    networks:
      back_network:
        ipv4_address: 172.16.58.13


networks:
  back_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.58.0/24
          gateway: 172.16.58.1
